version: '3.8'

services:
  mysql:
    volumes:
      - ~/Documents/projects/volumes/mysqlspringboot:/var/lib/mysql
    image: mysql:8.0
    container_name: mysql-springboot
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newrbms
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3308:3306
    networks:
      - newrbms-network

  newrbms-backend:
    build:
      context: .
    container_name: newrbms-backend
    ports:
      - 8091:8091
    volumes:
      - .:/usr/src/app
      - ~/.m2:/root/.m2
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/newrbms
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      JWT_SECRET: basefilejwtsecret
    depends_on:
      - mysql
    networks:
      - newrbms-network

networks:
  newrbms-network:
    name: newrbms-network
    external: true
    driver: bridge
