--UPDATE users
--SET storage_level_id = 1
--WHERE id = 1;
--
--UPDATE users
--SET storage_level_id = 2
--WHERE id = 2;
--
--UPDATE users
--SET storage_level_id = 3
--WHERE id = 3;
--
--UPDATE users
--SET storage_level_id = 4
--WHERE id = 4;
