--INSERT INTO location_user_groups (name,description)
--VALUES
--	 ('asd',''),
--	 ('New Group','');
--
--INSERT INTO location_user_group_users (group_id,user_id)
--VALUES
--	 (1,1),
--	 (2,1),
--	 (2,3),
--	 (2,4);
