CREATE TABLE IF NOT EXISTS customers (
    id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    customer_id     BIGINT UNSIGNED NOT NULL,
    name            VARCHAR(255) NOT NULL,
    company         VARCHAR(255) NOT NULL,
    email           VARCHAR(255),
    phone           VARCHAR(50),
    username        VARCHAR(255),
    street1         VARCHAR(255),
    street2         VARCHAR(255),
    street3         VARCHAR(255),
    city            VARCHAR(255),
    state           VARCHAR(255),
    postal_code     VARCHAR(50),
    country         VARCHAR(100),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,

    PRIMARY KEY (id),
    INDEX (name),
    INDEX (postal_code),
    UNIQUE (customer_id)
);

CREATE TABLE IF NOT EXISTS orders (
    id                          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_id                    VARCHAR(255) NOT NULL,
    order_number                VARCHAR(255) NOT NULL,
    order_key                   VARCHAR(255),
    order_date                  TIMESTAMP,
    create_date                 TIMESTAMP,
    modify_date                 TIMESTAMP,
    payment_date                TIMESTAMP,
    ship_by_date                TIMESTAMP,
    order_status                VARCHAR(100),
    customer_id                 BIGINT UNSIGNED,
    ship_to_customer_id         BIGINT UNSIGNED,
    order_total                 DECIMAL(10, 2),
    amount_paid                 DECIMAL(10, 2),
    tax_amount                  DECIMAL(10, 2),
    shipping_amount             DECIMAL(10, 2),
    payment_method              VARCHAR(100),
    carrier_code                VARCHAR(100),
    tracking_number             VARCHAR(255),
    confirmation                VARCHAR(100),
    requested_shipping_service  VARCHAR(255),
    service_code                VARCHAR(100),
    package_code                VARCHAR(100),
    customer_notes              TEXT,
    internal_notes              TEXT,
    created_at                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    INDEX (customer_id),
    INDEX (order_id),
    INDEX (tracking_number),
    FOREIGN KEY (customer_id)               REFERENCES customers(id),
    UNIQUE (order_id)
);

CREATE TABLE IF NOT EXISTS order_items (
    id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_id        BIGINT UNSIGNED NOT NULL,
    sku             VARCHAR(100),
    name            VARCHAR(255),
    quantity        INT,
    unit_price      DECIMAL(10, 2),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,

    PRIMARY KEY (id),
    INDEX (order_id),
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);
