CREATE TABLE IF NOT EXISTS field_groups (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    enabled BIT DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    INDEX idx_name (name)
);

CREATE TABLE IF NOT EXISTS fields (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    data_type VARCHAR(255) NOT NULL,
    field_type VARCHAR(255) NOT NULL,
    field_groups_id BIGINT UNSIGNED,
    is_multiple BIT DEFAULT 0 NOT NULL,
    enabled BIT DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    INDEX idx_field_groups_id (field_groups_id),
    FOREIGN KEY (field_groups_id) REFERENCES field_groups (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS values_data (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    value_data VARCHAR(255) NOT NULL UNIQUE,
    enabled BIT DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS fields_values (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    values_data_id BIGINT UNSIGNED,
    fields_id BIGINT UNSIGNED,
    score DOUBLE,
    enabled BIT DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    INDEX (fields_id),
    INDEX (values_data_id),
    FOREIGN KEY (fields_id) REFERENCES fields (id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (values_data_id) REFERENCES values_data (id) ON DELETE CASCADE ON UPDATE CASCADE
);
