INSERT INTO models (name,description,identifier,enabled,needs_mpn,status,approved_by,categories_id,created_by,deleted_at)
VALUES
	 ('8265NGW',NULL,NULL,1,0,NULL,NULL,14,1,NULL),
	 ('Battery for CF-54',NULL,NULL,1,1,NULL,NULL,4,1,NULL),
	 ('Battery for CF-54 (Media Bay 2nd Battery Pack)',NULL,NULL,1,1,NULL,NULL,4,1,NULL),
	 ('Bezel for CF-54',NULL,NULL,1,0,NULL,NULL,6,1,NULL),
	 ('Bottom Decal for CF-54',NULL,NULL,1,0,NULL,NULL,10,1,NULL),
	 ('Camera for CF-54',NULL,NULL,1,0,NULL,NULL,8,1,NULL),
	 ('Camera Sticker for CF-54',NULL,NULL,1,0,NULL,NULL,6,1,NULL),
	 ('CF-54',NULL,NULL,1,1,NULL,NULL,2,1,NULL),
	 ('Contactless Smart Card Reader for Cf-54',NULL,NULL,1,0,NULL,NULL,8,1,NULL),
	 ('Dell Latitude 5430 Rugged',NULL,NULL,1,0,NULL,NULL,2,1,NULL),
	 ('dGPS ublox for CF-54',NULL,NULL,1,0,NULL,NULL,7,1,NULL),
	 ('Docking Connector for CF-54',NULL,NULL,1,0,NULL,NULL,8,1,NULL),
	 ('Dummy for CF-54',NULL,NULL,1,0,NULL,NULL,6,1,NULL),
	 ('DVD Drive for CF-54',NULL,NULL,1,0,NULL,NULL,8,1,NULL),
	 ('EM7355',NULL,NULL,1,0,NULL,NULL,15,1,NULL),
	 ('Fingerprint Plastic Cover for CF-54',NULL,NULL,1,0,NULL,NULL,6,1,NULL),
	 ('Fingerprint scanner for CF-54',NULL,NULL,1,0,NULL,NULL,8,1,NULL),
	 ('Flat Bottom Cover for CF-54',NULL,NULL,1,0,NULL,NULL,6,1,NULL),
	 ('Handle for CF-54',NULL,NULL,1,0,NULL,NULL,6,1,NULL),
	 ('Hinge Cover for CF-54',NULL,NULL,1,0,NULL,NULL,6,1,NULL),
	 ('Insertable Smart Card Reader for CF-54',NULL,NULL,1,0,NULL,NULL,8,1,NULL),
	 ('Keyboard for CF-54',NULL,NULL,1,0,NULL,NULL,11,1,NULL),
	 ('Latch for CF-54',NULL,NULL,1,0,NULL,NULL,6,1,NULL),
	 ('Left Back Cover for CF-54',NULL,NULL,1,0,NULL,NULL,6,1,NULL),
	 ('Left Hinge for CF-54',NULL,NULL,1,0,NULL,NULL,6,1,NULL),
	 ('Mouse Pad for CF-54',NULL,NULL,1,0,NULL,NULL,8,1,NULL),
	 ('Non-flat Bottom Cover for CF-54',NULL,NULL,1,0,NULL,NULL,6,1,NULL),
	 ('Optional USB Port for CF-54',NULL,NULL,1,0,NULL,NULL,8,1,NULL),
	 ('Palmrest for CF-54',NULL,NULL,1,0,NULL,NULL,6,1,NULL),
	 ('Plastic Feet for CF-54',NULL,NULL,1,0,NULL,NULL,6,1,NULL),
	 ('RAM',NULL,NULL,1,1,NULL,NULL,12,1,NULL),
	 ('RAM model 2',NULL,NULL,1,1,NULL,NULL,12,1,NULL),
	 ('Right Back Cover for CF-54',NULL,NULL,1,0,NULL,NULL,6,1,NULL),
	 ('Right Hinge for CF-54',NULL,NULL,1,0,NULL,NULL,6,1,NULL),
	 ('Rubber Feet for CF-54',NULL,NULL,1,0,NULL,NULL,6,1,NULL),
	 ('Screen for CF-54',NULL,NULL,1,0,NULL,NULL,13,1,NULL),
	 ('Serial Port for CF-54',NULL,NULL,1,0,NULL,NULL,8,1,NULL),
	 ('Speakers for CF-54',NULL,NULL,1,0,NULL,NULL,8,1,NULL),
	 ('SSD',NULL,NULL,1,1,NULL,NULL,9,1,NULL),
	 ('Top Cover for CF-54',NULL,NULL,1,0,NULL,NULL,6,1,NULL),
	 ('USB Right Side Cover for CF-54',NULL,NULL,1,0,NULL,NULL,6,1,NULL),
	 ('VGA Port for CF-54',NULL,NULL,1,0,NULL,NULL,8,1,NULL),
	 ('WLAN Antenna Cover for CF-54',NULL,NULL,1,0,NULL,NULL,6,1,NULL);

INSERT INTO model_fields_values (fields_values_id,models_id) VALUES
	 (23,8),
	 (91,8),
	 (24,10),
	 (91,10),
	 (16,39);
