name: CI
on:
  push:
    branches: [ beta ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git pull, run Migrations and restart services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BETA_SSH_HOST }}
          username: ${{ secrets.BETA_SSH_USER }}
          key: ${{ secrets.BETA_SSH_KEY }}
          port: ${{ secrets.BETA_SSH_PORT }}
          script: |
            cd /home/deploy/documents/projects/spring-boot-rest-api
            git pull
            sh update.sh
